"""Increase description field size

Revision ID: 2f7bd8ff3fe5
Revises: f4814fbfb001
Create Date: 2025-06-16 00:53:45.286275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f7bd8ff3fe5'
down_revision = 'f4814fbfb001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               type_=sa.Enum('ADMIN', 'ÉVALUATEUR', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'ÉVALUATEUR', name='role'),
               type_=mysql.ENUM('ADMIN', 'USER'),
               existing_nullable=False)

    # ### end Alembic commands ###
